image: node:12

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm ci
  only:
    - master

test:
  stage: test
  script:
    - npm run test
  only:
    - master

build site:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist
  only:
    - master

deploy site:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --dir dist --prod
  dependencies:
    - build site
  only:
    - master
