image: google/cloud-sdk:alpine

deploy_production:
  stage: deploy
  environment:
    name: Production
  only:
  - master
  script:
  - echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $GCP_PROJECT_ID app deploy app.production.yaml

deploy_staging:
  stage: deploy
  environment:
    name: Staging
  only:
  - staging
  script:
  - echo $GCP_SERVICE_ACCOUNT_KEY > /tmp/$CI_PIPELINE_ID.json
  - gcloud auth activate-service-account --key-file /tmp/$CI_PIPELINE_ID.json
  - gcloud --quiet --project $GCP_PROJECT_ID app deploy app.staging.yaml

after_script:
  - rm /tmp/$CI_PIPELINE_ID.json
