image: node:10.16.3

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - setup
  - test
  - build
  - deploy

setup:
  stage: setup
  script:
    - npm ci
  only:
    - master

test:
  stage: test
  script:
    - npm run test
  only:
    - master

build-platform:
  stage: build
  script:
    - npm run generate
  artifacts:
    paths:
      - dist
  only:
    - master

build-storybook:
  stage: build
  script:
    - npm run build-storybook
  artifacts:
    paths:
      - storybook-static
  only:
    - master

deploy platform:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build-platform
  only:
    - master

deploy storybook:
  stage: deploy
  script:
    - npm i -g netlify-cli
    - netlify deploy --site $NETLIFY_STORYBOOK_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - build-storybook
  only:
    - master
