image: google/cloud-sdk:alpine

deploy_production:
  stage: deploy
  environment:
    name: Production
  only:
  - master
  script:
  - echo $GCP_SERVICE_ACCOUNT_KEY
  - gcloud auth activate-service-account  --key-file $GCP_SERVICE_ACCOUNT_KEY
  - gcloud --quiet --project $GCLOUD_PROJECT_ID app deploy app.yaml

deploy_staging:
  stage: deploy
  environment:
    name: Staging
  only:
  - staging
  script:
  - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
  - gcloud --quiet --project $GCLOUD_PROJECT_ID app deploy staging-app.yaml
