image: google/cloud-sdk:alpine

cache:
  paths:
    - node_modules/

before_script:
  - apk update
  - apk add nodejs npm
  - npm i

stages:
  - build
  - test
  - staging
  - production

build:
  stage: build
  environment:
    name: build
  script:
    - npm run build

test:
  stage: test
  environment:
    name: test
  script:
    - npm run test

deploy to staging:
  stage: staging
  environment:
    name: staging
  only:
    - staging
  script:
    - npm run build
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    - gcloud app deploy app.staging.yaml --quiet --project $GCP_PROJECT_ID

deploy to production:
  stage: production
  environment:
    name: production
  only:
    - master
  script:
    - npm run build
    - gcloud auth activate-service-account --key-file $GCP_SERVICE_ACCOUNT_KEY
    - gcloud app deploy app.production.yaml --quiet --project $GCP_PROJECT_ID
