image: google/cloud-sdk:alpine

deploy_production:
  stage: deploy
  environment:
    name: Production
  only:
  - master
  script:
  - gcloud auth activate-service-account — key-file $SERVICE_ACCOUNT_KEY
  - gcloud --quiet --project $PROJECT_ID app deploy app.yaml

deploy_staging:
  stage: deploy
  environment:
    name: Staging
  only:
  - staging
  script:
  - gcloud auth activate-service-account — key-file $SERVICE_ACCOUNT_KEY
  - gcloud --quiet --project $PROJECT_ID app deploy staging-app.yaml
