allowBuilds:
  '@fortawesome/fontawesome-common-types': true
  '@fortawesome/fontawesome-svg-core': true
  '@fortawesome/free-brands-svg-icons': true
  '@fortawesome/free-solid-svg-icons': true
  bootstrap-vue: true
  core-js: true
  deasync: true
  fsevents: true
  nuxt: true
  protobufjs: true
